[package]
name = "worker"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
bicycle-protocol = { path = "../../crates/protocol" }
bicycle-core = { path = "../../crates/core" }
bicycle-runtime = { path = "../../crates/runtime" }
bicycle-network = { path = "../../crates/network" }
bicycle-state = { path = "../../crates/state" }
bicycle-operators = { path = "../../crates/operators" }
bicycle-connectors = { path = "../../crates/connectors", features = ["socket"] }
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
clap = { version = "4", features = ["derive"] }
dashmap.workspace = true
parking_lot.workspace = true
uuid.workspace = true
hostname.workspace = true
serde.workspace = true
serde_json.workspace = true
bincode.workspace = true
tokio-stream = { workspace = true, features = ["net"] }
libloading = "0.8"
